import { Link } from 'react-router-dom';
import { ArrowRight, ChevronRight, Copy, Database, Network, Route, Workflow } from 'lucide-react';
import { SennetLogo, SennetMark } from '@/components/brand/SennetLogo';
import { EvidenceJourney } from '@/components/marketing/EvidenceJourney';

const capabilities = [
  ['Infrastructure & apps','Traces, logs, metrics, service dependencies','Available'],
  ['Autonomous systems','Runs, handoffs, retries, token and cost provenance','Available'],
  ['Financial operations','Exact decimals, sequence gaps, lifecycle inspection','Bounded'],
  ['Network telemetry','Linux traffic counters and flow observations','Linux'],
  ['Streaming data plane','Kafka ingestion and ClickHouse analytics','Evaluation'],
  ['High availability','Replicated, multi-region production topology','Not established'],
];

export function HomePage(){
  const copyInstall = () => void navigator.clipboard?.writeText('git clone <your-sennet-repository> && cd Sennet');
  return <div className="site-shell">
    <header className="site-nav"><SennetLogo/><nav aria-label="Primary"><a href="#journey">Product</a><a href="#architecture">Architecture</a><Link to="/docs">Docs</Link></nav><div><Link to="/login" className="nav-login">Sign in</Link><Link to="/login" className="button button--small">Open workspace <ArrowRight/></Link></div></header>
    <main>
      <section className="opening">
        <div className="opening__copy"><span className="section-index">CONNECTED OBSERVABILITY / SELF-HOSTED</span><h1>Follow the<br/><em>evidence.</em></h1><p>Sennet reconstructs what happened across distributed infrastructure, agents, network traffic, and financial workflows—without pretending correlation is causality.</p><div className="opening__actions"><Link className="button" to="/login">Investigate your systems <ArrowRight/></Link><Link className="text-link" to="/docs/quickstart">Ingest the first signal <ChevronRight/></Link></div></div>
        <div className="opening__signal" aria-label="A routed signal becoming structured evidence"><svg viewBox="0 0 720 560" role="img"><title>A request branches through agents and services before converging on a verified result.</title><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0l6 3-6 3z"/></marker></defs><path className="route route--base" d="M40 280H165C220 280 214 115 290 115h95c75 0 75 94 145 94h132M165 280c58 0 55 160 127 160h90c78 0 76-119 148-119h132"/><path className="route route--signal" d="M40 280H165C220 280 214 115 290 115h95c75 0 75 94 145 94h132" markerEnd="url(#arrow)"/><g>{[[40,280],[165,280],[290,115],[385,115],[530,209],[662,209],[292,440],[382,440],[530,321],[662,321]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r={i===0||i===9?9:5}/>)}</g><text x="40" y="258">REQUEST</text><text x="272" y="88">PARALLEL HANDOFFS</text><text x="508" y="185">SERVICE EVIDENCE</text><text x="270" y="478">NETWORK + RISK</text><text x="585" y="356">RESULT</text></svg><div className="opening__readout"><span><i/> TRACE CONNECTED</span><code>392.18 ms</code><code>12 observed spans</code></div></div>
        <div className="opening__rail" aria-hidden><span>REQUEST</span><i/><span>DECISIONS</span><i/><span>DEPENDENCIES</span><i/><span>OUTCOME</span></div>
      </section>
      <EvidenceJourney/>
      <section className="product-views"><div className="section-heading"><span className="section-index">02 / CHANGE PERSPECTIVE</span><h2>The query stays.<br/>The view changes.</h2><p>Move between time series, distributions, pipelines, agent runs, topology, and transmission timelines while preserving scope and selection.</p></div><div className="view-grid"><article className="view-card view-card--wide"><header><span>TRANSMISSION TIMELINE</span><b>Hours → milliseconds</b></header><div className="mini-timeline">{['gateway','supervisor','model / tool','payment service','settlement'].map((label,index)=><div key={label}><span>{label}</span><i style={{marginLeft:`${index*7}%`,width:`${45-index*4}%`}}/></div>)}</div></article><article className="view-card"><header><span>PIPELINE</span><b>Stage loss</b></header><div className="mini-tunnel">{[100,96,92,88,88,84].map((size,index)=><i key={`${size}-${index}`} style={{width:`${size}%`}}><span>{['accepted','validated','queued','processed','stored','queried'][index]}</span><b>{size}k</b></i>)}</div></article><article className="view-card"><header><span>AGENT RUN</span><b>Critical path</b></header><div className="mini-dag"><i/><i/><i/><i/><i/><svg viewBox="0 0 300 130"><path d="M30 65h55l45-35m-45 35 45 35m0-70h60l45 35m-105 35h60l45-35"/></svg></div></article></div></section>
      <section className="architecture" id="architecture"><div className="section-heading"><span className="section-index">03 / ARCHITECTURE</span><h2>Evidence has a route.</h2><p>Each boundary has a different durability and trust contract. Sennet names those boundaries instead of collapsing them into a “live” badge.</p></div><div className="architecture__map">{[[Route,'Collect','OTLP + domain events','Persistent queues'],[Network,'Admit','Authenticated gateway','Bounded validation'],[Workflow,'Process','Durable event log','At-least-once'],[Database,'Investigate','ClickHouse + query service','Tenant + time bounded']].map(([Icon,title,detail,boundary],index)=><article key={String(title)}><span>{String(index+1).padStart(2,'0')}</span><Icon/><h3>{title as string}</h3><p>{detail as string}</p><small>{boundary as string}</small></article>)}</div></section>
      <section className="capability-section"><div className="section-heading"><span className="section-index">04 / CURRENT BOUNDARIES</span><h2>Specific by design.<br/>Honest by default.</h2></div><div className="capability-table" role="table" aria-label="Capability status"><div className="capability-row capability-row--head" role="row"><span>Domain</span><span>Current surface</span><span>Status</span></div>{capabilities.map(row=><div className="capability-row" role="row" key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><em className={row[2].startsWith('Not')?'is-unavailable':''}>{row[2]}</em></div>)}</div><p className="truth-note">Measured local evaluation: 12,000 accepted / durable / stored events with zero lost in the recorded release harness. This is not a production capacity or availability claim.</p></section>
      <section className="install-path"><div><span className="section-index">05 / FIRST SIGNAL</span><h2>From checkout<br/>to evidence.</h2><p>Run the local evaluation stack, authenticate, then send explicit fixture or real OTLP data. Demo data is never substituted into a workspace.</p><Link to="/docs/quickstart" className="text-link">Read the complete quickstart <ArrowRight/></Link></div><ol><li><span>01</span><div><strong>Start the control and query service</strong><code>cd backend &amp;&amp; go run .</code></div></li><li><span>02</span><div><strong>Start the product workspace</strong><code>cd web &amp;&amp; npm ci &amp;&amp; npm run dev</code></div></li><li><span>03</span><div><strong>Send a clearly labelled evaluation fixture</strong><code>python examples/send_fixture.py</code></div></li></ol><button className="copy-action" onClick={copyInstall}><Copy/> Copy repository start</button></section>
      <section className="closing"><SennetMark/><span className="section-index">OBSERVE THE WHOLE SYSTEM</span><h2>Find the exact<br/>dependency that changed the outcome.</h2><Link to="/login" className="button">Open the workspace <ArrowRight/></Link></section>
    </main>
    <footer className="site-footer"><SennetLogo/><p>Self-hosted connected observability.<br/>Capacity depends on your measured deployment.</p><nav><Link to="/docs">Documentation</Link><Link to="/docs/architecture">Architecture</Link><a href="https://github.com" rel="noreferrer">Source</a></nav><span>© 2026 Sennet</span></footer>
  </div>;
}
