import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ExternalLink, GripVertical, Plus, Save } from 'lucide-react';
import { api } from '@/api/client';
import { useAuth } from '@/hooks/useAuth';
import { useInvestigationState } from './state';
import { QueryState } from './QueryState';

interface Panel {id:string;title:string;signal:string;operation:string}
interface SavedView {id:string;name:string;path:string;range:string;signal:string;search:string;service:string}
interface Version extends SavedView {version_id:string;created_at:number;panels?:Panel[];brush?:string}

export function DashboardComposer() {
  const {user}=useAuth(); const {state,update,params}=useInvestigationState(); const [panels,setPanels]=useState<Panel[]>([{id:'activity',title:'Signal activity',signal:'trace',operation:'count'},{id:'errors',title:'Error rate',signal:'trace',operation:'rate'},{id:'services',title:'Slowest services',signal:'trace',operation:'p95'}]); const [name,setName]=useState('Investigation dashboard'); const [message,setMessage]=useState(''); const [selected,setSelected]=useState(''); const brush=params.get('brush')||'';
  const views=useQuery({queryKey:['dashboards',user?.tenant],queryFn:async({signal})=>(await api.get<SavedView[]>('/api/dashboards',{signal})).data});
  const versions=useQuery({queryKey:['dashboard-versions',selected],enabled:!!selected,queryFn:async({signal})=>(await api.get<Version[]>('/api/dashboard-versions',{signal,params:{id:selected}})).data});
  const save=async()=>{try{const response=await api.post<SavedView>('/api/dashboards',{id:selected||undefined,name,path:'/dashboard',range:state.range,service:state.service,search:state.search,signal:'',timezone:state.timezone,environment:state.environment,brush,panels,variables:{environment:state.environment,service:state.service}});setSelected(response.data.id);setMessage('Dashboard and immutable version saved.');void views.refetch();void versions.refetch()}catch{setMessage('Dashboard could not be saved. Editor access is required.')}};
  return <><section className="panel dashboard-builder"><div className="panel-heading"><div><h2>Dashboard composition</h2><span>Versioned panels · synchronized time · persisted linked brush</span></div><button onClick={()=>void save()}><Save size={15}/>Save</button></div><div className="builder-toolbar"><input aria-label="Dashboard name" value={name} onChange={event=>setName(event.target.value)}/><label>Environment <input value={state.environment} onChange={event=>update({environment:event.target.value})}/></label><label>Service <input value={state.service} onChange={event=>update({service:event.target.value})}/></label><label>Linked brush <select value={brush} onChange={event=>update({brush:event.target.value})}><option value="">Full window</option><option value="first-half">First half</option><option value="second-half">Second half</option></select></label><button onClick={()=>setPanels(value=>[...value,{id:crypto.randomUUID(),title:`Panel ${value.length+1}`,signal:'metric',operation:'avg'}])}><Plus/>Add panel</button></div><div className="panel-grid">{panels.map((panel,index)=><article key={panel.id} tabIndex={0}><header><GripVertical/><input aria-label={`Panel ${index+1} name`} value={panel.title} onChange={event=>setPanels(value=>value.map(item=>item.id===panel.id?{...item,title:event.target.value}:item))}/></header><div className="panel-definition"><label>Signal <select value={panel.signal} onChange={event=>setPanels(value=>value.map(item=>item.id===panel.id?{...item,signal:event.target.value}:item))}><option>trace</option><option>log</option><option>metric</option><option>flow</option></select></label><label>Operation <select value={panel.operation} onChange={event=>setPanels(value=>value.map(item=>item.id===panel.id?{...item,operation:event.target.value}:item))}><option>count</option><option>avg</option><option>rate</option><option>p95</option></select></label><button onClick={()=>update({inspect:panel.id})}>Inspect query/source <ExternalLink/></button></div></article>)}</div>{message?<p className="notice" role="status">{message}</p>:null}</section><section className="panel"><div className="panel-heading"><h2>Saved dashboards and versions</h2><span>{views.data?.length||0} resources</span></div>{views.isPending?<QueryState kind="loading"/>:views.isError?<QueryState kind="failed"/>:views.data?.length?<div className="saved-grid">{views.data.map(view=><button key={view.id} onClick={()=>setSelected(view.id)}>{view.name} · versions →</button>)}</div>:<QueryState kind="empty" title="No saved dashboards" detail="Save the composition above."/>}{selected?<div className="version-list">{versions.isPending?<QueryState kind="loading"/>:versions.data?.map(version=><button key={version.version_id} onClick={()=>{if(version.panels)setPanels(version.panels);update({range:version.range||state.range,service:version.service||'',brush:version.brush||''})}}>Version {new Date(version.created_at).toLocaleString()}</button>)}</div>:null}</section></>;
}
