import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Copy, ExternalLink, GripVertical, Maximize2, Minimize2, Plus, Presentation, Save, Trash2 } from 'lucide-react';
import { api } from '@/api/client';
import { useAuth } from '@/hooks/useAuth';
import { useInvestigationState } from './state';
import { QueryState } from './QueryState';
import type { AnalyticalResponse } from './types';
import { VisualizationStudio } from './visualizations';
import { compatibleVisualizations, type VisualizationId } from './visualizationRegistry';

interface Panel {id:string;title:string;signal:string;operation:string;visualization:VisualizationId;width:1|2}
interface SavedView {id:string;name:string;path:string;range:string;signal:string;search:string;service:string}
interface Version extends SavedView {version_id:string;created_at:number;panels?:Panel[];brush?:string}

type PanelTemplate=[string,string,string,string,VisualizationId,1|2];
const templates:Record<string,PanelTemplate[]>={
  'Platform overview':[['activity','Signal activity','trace','count','area',2],['errors','Error distribution','trace','p95','distribution',1],['pipeline','Ingestion route','flow','sum','pipeline',1]],
  'Ingestion health':[['accepted','Accepted volume','flow','sum','tunnel',2],['lag','Pipeline lag','flow','p95','line',1],['topology','Processing topology','flow','count','topology',1]],
  'Distributed service investigation':[['latency','Service latency','trace','p95','line',2],['topology','Dependencies','trace','count','topology',1],['transmission','Span transmission','trace','p95','transmission',1]],
  'Multi-agent operations':[['runs','Run timeline','agent','count','agent-workflow',2],['tokens','Token efficiency','agent','sum','radar',1],['handoffs','Handoffs','agent','p95','transmission',1]],
  'Model and token efficiency':[['cost','Cost distribution','agent','sum','distribution',1],['quality','Quality dimensions','agent','avg','radar',1],['latency','Model latency','agent','p95','line',2]],
  'Financial transaction operations':[['lifecycle','Transaction lifecycle','finance','count','finance-lifecycle',2],['delay','Settlement delay','finance','p95','distribution',1],['timeline','Event time','finance','count','transmission',1]],
  'SLO and incident review':[['availability','Availability','trace','avg','line',2],['errors','Errors','trace','count','stacked',1],['critical','Critical path','trace','p95','transmission',1]],
};
const makeTemplate=(name:string)=>templates[name].map(row=>({id:row[0] as string,title:row[1] as string,signal:row[2] as string,operation:row[3] as string,visualization:row[4] as VisualizationId,width:row[5] as 1|2}));

function DashboardPanel({panel,onUpdate,onDuplicate,onDelete,onInspect,mode}:{panel:Panel;onUpdate:(next:Panel)=>void;onDuplicate:()=>void;onDelete:()=>void;onInspect:()=>void;mode:'edit'|'present'}){
  const {state}=useInvestigationState();
  const query=useQuery({queryKey:['panel-query',panel.id,panel.signal,panel.operation,state.range,state.service],queryFn:async({signal})=>{const to=Date.now();return(await api.post<AnalyticalResponse>('/api/query',{version:'v1',signal:panel.signal,from:to-Number(state.range),to,service:state.service,operation:panel.operation,group_by:['service'],step_ms:0,budget:{max_rows:50000,max_bytes:8388608,max_cpu_ms:5000,timeout_ms:5000}},{signal})).data},retry:1});
  const options=compatibleVisualizations(panel.signal);
  return <article className={`dashboard-panel span-${panel.width}`} tabIndex={0} draggable={mode==='edit'} data-panel={panel.id}><header>{mode==='edit'?<GripVertical className="drag-handle" aria-label="Drag panel"/>:null}<input aria-label={`${panel.title} panel name`} readOnly={mode==='present'} value={panel.title} onChange={event=>onUpdate({...panel,title:event.target.value})}/>{mode==='edit'?<div className="panel-actions"><button title={panel.width===2?'Make compact':'Make wide'} onClick={()=>onUpdate({...panel,width:panel.width===2?1:2})}>{panel.width===2?<Minimize2/>:<Maximize2/>}</button><button title="Duplicate panel" onClick={onDuplicate}><Copy/></button><button title="Delete panel" onClick={onDelete}><Trash2/></button></div>:null}</header>{mode==='edit'?<div className="panel-config"><label>Signal<select value={panel.signal} onChange={event=>{const signal=event.target.value;onUpdate({...panel,signal,visualization:compatibleVisualizations(signal)[0]?.id||'line'})}}>{['trace','log','metric','flow','agent','finance'].map(value=><option key={value}>{value}</option>)}</select></label><label>Aggregate<select value={panel.operation} onChange={event=>onUpdate({...panel,operation:event.target.value})}>{['count','avg','sum','rate','p50','p95','p99'].map(value=><option key={value}>{value}</option>)}</select></label><label>View<select value={panel.visualization} onChange={event=>onUpdate({...panel,visualization:event.target.value as VisualizationId})}>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><button onClick={onInspect}><ExternalLink/> Query</button></div>:null}{query.isPending?<QueryState kind="loading"/>:query.isError?<QueryState kind="failed" retry={()=>void query.refetch()}/>:query.data?.points?.length?<VisualizationStudio signal={panel.signal} points={query.data.points} visualization={panel.visualization} onVisualizationChange={value=>onUpdate({...panel,visualization:value})} title={panel.title}/>:<QueryState kind="empty" detail="No backend aggregates matched this panel scope."/>}</article>;
}

export function DashboardComposer() {
  const {user}=useAuth(); const {state,update,params}=useInvestigationState(); const [panels,setPanels]=useState<Panel[]>(()=>makeTemplate('Platform overview')); const [name,setName]=useState('Platform overview'); const [message,setMessage]=useState(''); const [selected,setSelected]=useState(''); const [dragged,setDragged]=useState(''); const [inspect,setInspect]=useState<Panel>(); const mode=(params.get('mode')==='present'?'present':'edit') as 'edit'|'present'; const brush=params.get('brush')||'';
  const views=useQuery({queryKey:['dashboards',user?.tenant],queryFn:async({signal})=>(await api.get<SavedView[]>('/api/dashboards',{signal})).data});
  const versions=useQuery({queryKey:['dashboard-versions',selected],enabled:!!selected,queryFn:async({signal})=>(await api.get<Version[]>('/api/dashboard-versions',{signal,params:{id:selected}})).data});
  const save=async()=>{try{const response=await api.post<SavedView>('/api/dashboards',{id:selected||undefined,name,path:'/dashboard',range:state.range,service:state.service,search:state.search,signal:'',timezone:state.timezone,environment:state.environment,brush,panels,variables:{environment:state.environment,service:state.service,tenant:state.tenant}});setSelected(response.data.id);setMessage('Dashboard and immutable version saved to the workspace.');void views.refetch();void versions.refetch()}catch{setMessage('Dashboard could not be saved. Editor access is required.')}};
  const updatePanel=(panel:Panel)=>setPanels(value=>value.map(item=>item.id===panel.id?panel:item));
  const reorder=(target:string)=>{if(!dragged||dragged===target)return;setPanels(value=>{const from=value.findIndex(item=>item.id===dragged),to=value.findIndex(item=>item.id===target);const next=[...value];const [item]=next.splice(from,1);next.splice(to,0,item);return next});setDragged('')};
  return <><section className={`dashboard-builder ${mode==='present'?'is-presenting':''}`}><div className="dashboard-toolbar"><div><span className="eyebrow">COMPOSABLE DASHBOARD</span><input aria-label="Dashboard name" readOnly={mode==='present'} value={name} onChange={event=>setName(event.target.value)}/><small>Shared query, time, timezone, environment, service, and tenant state</small></div><div><button onClick={()=>update({mode:mode==='edit'?'present':'edit'})}><Presentation/>{mode==='edit'?'Present':'Edit'}</button>{mode==='edit'?<button className="primary-action" onClick={()=>void save()}><Save/>Save dashboard</button>:null}</div></div>{mode==='edit'?<div className="builder-toolbar"><label>Template<select value={templates[name]?name:''} onChange={event=>{const template=event.target.value;if(template){setName(template);setPanels(makeTemplate(template))}}}><option value="">Custom</option>{Object.keys(templates).map(template=><option key={template}>{template}</option>)}</select></label><label>Environment<input value={state.environment} placeholder="All" onChange={event=>update({environment:event.target.value})}/></label><label>Service<input value={state.service} placeholder="All" onChange={event=>update({service:event.target.value})}/></label><label>Linked brush<select value={brush} onChange={event=>update({brush:event.target.value})}><option value="">Full window</option><option value="first-half">First half</option><option value="second-half">Second half</option></select></label><button onClick={()=>setPanels(value=>[...value,{id:crypto.randomUUID(),title:`Panel ${value.length+1}`,signal:'metric',operation:'avg',visualization:'line',width:1}])}><Plus/>Add panel</button></div>:null}{state.environment?<QueryState kind="partial" title="Environment variable retained, not applied" detail="The analytical query contract has no environment field. This variable is persisted and shared in the URL, while panel results remain workspace-wide until the backend exposes the filter."/>:null}<div className="dashboard-grid">{panels.map(panel=><div key={panel.id} className={`panel-drop span-${panel.width}`} onDragStart={()=>setDragged(panel.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>reorder(panel.id)}><DashboardPanel panel={panel} mode={mode} onUpdate={updatePanel} onInspect={()=>setInspect(panel)} onDuplicate={()=>setPanels(value=>[...value,{...panel,id:crypto.randomUUID(),title:`${panel.title} copy`}])} onDelete={()=>setPanels(value=>value.filter(item=>item.id!==panel.id))}/></div>)}</div>{message?<p className="notice" role="status">{message}</p>:null}</section>
    {mode==='edit'?<section className="panel saved-dashboards"><div className="panel-heading"><h2>Saved dashboards and versions</h2><span>{views.data?.length||0} persisted resources</span></div>{views.isPending?<QueryState kind="loading"/>:views.isError?<QueryState kind="failed"/>:views.data?.length?<div className="saved-grid">{views.data.map(view=><button key={view.id} onClick={()=>setSelected(view.id)}>{view.name}<span>Versions →</span></button>)}</div>:<QueryState kind="empty" title="No saved dashboards" detail="Save the composition above to create a backend resource."/>}{selected?<div className="version-list">{versions.isPending?<QueryState kind="loading"/>:versions.data?.map(version=><button key={version.version_id} onClick={()=>{if(version.panels)setPanels(version.panels);setName(version.name);update({range:version.range||state.range,service:version.service||'',brush:version.brush||''})}}>Version {new Date(version.created_at).toLocaleString()}</button>)}</div>:null}</section>:null}
    {inspect?<div className="query-inspector" role="dialog" aria-modal="true" aria-labelledby="query-inspector-title"><div><header><h2 id="query-inspector-title">Inspect query</h2><button autoFocus onClick={()=>setInspect(undefined)}>Close</button></header><pre>{JSON.stringify({version:'v1',signal:inspect.signal,operation:inspect.operation,range:state.range,timezone:state.timezone,environment:{value:state.environment||null,applied:false,reason:'unsupported by current query contract'},service:state.service||null,tenant:'server-derived',visualization:inspect.visualization,budget:{max_rows:50000,max_bytes:8388608,timeout_ms:5000}},null,2)}</pre><p>Tenant scope is authenticated and derived by the backend. The selected view is client presentation; aggregation stays server-side. Environment remains saved but is explicitly not applied.</p></div></div>:null}
  </>;
}
