/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useRef, useState } from 'react';
import { Columns3, CornerDownRight, Eye, EyeOff, ShieldCheck } from 'lucide-react';
import type { TelemetryEvent } from './types'; import { formatTime } from './state'; import { QueryState } from './QueryState';
const ROW=58, HEIGHT=464;
const allColumns = ['time','name','service','signal','duration','status','trace'] as const;
type Column = typeof allColumns[number];
export function EventTable({events,timezone,loading,nextCursor,cursor,onPage,onInspect}:{events:TelemetryEvent[];timezone:string;loading:boolean;nextCursor?:string;cursor?:string;onPage:(cursor:string)=>void;onInspect:(event:TelemetryEvent)=>void}) {
 const [visible,setVisible]=useState<Column[]>(['time','name','service','duration','status']); const [scrollTop,setScrollTop]=useState(0); const [columnsOpen,setColumnsOpen]=useState(false); const [context,setContext]=useState<string>(); const scroller=useRef<HTMLDivElement>(null);
 const start=Math.max(0,Math.floor(scrollTop/ROW)-4), count=Math.ceil(HEIGHT/ROW)+8, rows=events.slice(start,start+count);
 const contextRows=useMemo(()=>context?events.filter(e=>e.trace_id===context):[],[events,context]);
 useEffect(()=>{scroller.current?.scrollTo({top:0});setScrollTop(0)},[events]);
 const redacted=(e:TelemetryEvent)=>Object.keys(e.attributes||{}).some(k=>/redact|masked|scrubbed/i.test(k));
 return <section className="panel event-panel"><div className="panel-heading"><div><h2>Events</h2><span>{events.length} loaded · virtualized rows</span></div><div className="column-menu"><button aria-expanded={columnsOpen} onClick={()=>setColumnsOpen(v=>!v)}><Columns3 size={15}/>Columns</button>{columnsOpen&&<fieldset><legend>Visible columns</legend>{allColumns.map(c=><label key={c}><input type="checkbox" checked={visible.includes(c)} onChange={()=>setVisible(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])}/>{c}</label>)}</fieldset>}</div></div>
 {loading&&!events.length?<QueryState kind="loading"/>:!events.length?<QueryState kind="empty"/>:<><div className="virtual-head" style={{gridTemplateColumns:`repeat(${visible.length}, minmax(120px,1fr)) 84px`}}>{visible.map(c=><strong key={c}>{c}</strong>)}<strong>Actions</strong></div><div className="virtual-body" ref={scroller} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)} style={{height:HEIGHT}} role="table" aria-rowcount={events.length}><div style={{height:events.length*ROW,position:'relative'}}><div style={{transform:`translateY(${start*ROW}px)`}}>{rows.map(event=><div className="virtual-row" role="row" key={event.id} style={{gridTemplateColumns:`repeat(${visible.length}, minmax(120px,1fr)) 84px`,height:ROW}}>{visible.map(c=><div role="cell" key={c}>{c==='time'?<span className="mono">{formatTime(event.time,timezone)}</span>:c==='name'?<button className="text-button" onClick={()=>onInspect(event)}>{event.name||'Unnamed'}</button>:c==='duration'?(event.duration_ms?`${event.duration_ms.toFixed(2)} ms`:'—'):c==='trace'?(event.trace_id?<code>{event.trace_id.slice(0,12)}…</code>:'—'):c==='status'?<span className={`status-label ${event.status==='error'?'bad':''}`}>{event.status||'observed'} {redacted(event)&&<ShieldCheck aria-label="Redacted attributes" size={13}/>}</span>:event[c]||'—'}</div>)}<div className="row-actions"><button title="Expand trace context" aria-label={`Expand context for ${event.name}`} disabled={!event.trace_id} onClick={()=>setContext(context===event.trace_id?undefined:event.trace_id)}>{context===event.trace_id?<EyeOff size={14}/>:<Eye size={14}/>}</button><button aria-label={`Inspect ${event.name}`} onClick={()=>onInspect(event)}><CornerDownRight size={14}/></button></div>{context===event.trace_id&&<div className="context-row">{contextRows.length} events from this loaded page share the trace. Open the event for the complete bounded trace.</div>}</div>)}</div></div></div></>}
 <div className="pagination"><button disabled={!cursor} onClick={()=>onPage('')}>Newest page</button><span>Cursor pagination · changing filters cancels in-flight requests</span><button disabled={!nextCursor} onClick={()=>onPage(nextCursor||'')}>Older page →</button></div></section>;
}
