import { useState, useMemo, useEffect, useRef } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
import { RefreshCw, Search, ArrowUpRight, Save, X, Activity, ChevronRight } from 'lucide-react';
import { api } from '@/api/client';
import { useAuth } from '@/hooks/useAuth';
import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import { type TelemetryEvent, type EventPage, type Agent, formatNumber, signalNames } from './types';

export function Explorer({ signal='', topology=false }: {signal?:string;topology?:boolean}) {
 const {user}=useAuth();const [params,setParams]=useSearchParams();const [search,setSearch]=useState(params.get('search')||'');const [selected,setSelected]=useState<TelemetryEvent|null>(null);const [message,setMessage]=useState('');
 const range=params.get('range')||'3600000';const service=params.get('service')||'';const trace=params.get('trace_id')||'';const cursor=params.get('cursor')||'';const paused=params.get('paused')==='true';
 const query=useQuery({queryKey:['events',user?.tenant,signal,range,service,trace,cursor,params.get('search')],queryFn:async({signal:cancel})=>{const to=Date.now();const {data}=await api.get<EventPage>('/api/events',{signal:cancel,params:{from:to-Number(range),to,signal,service,trace_id:trace,search:params.get('search')||'',limit:200,cursor}});return data;},refetchInterval:paused||cursor?false:10000,retry:1});
 const summary=useQuery({queryKey:['summary',user?.tenant,signal,range,service,trace,params.get('search')],queryFn:async({signal:cancel})=>{const to=Date.now();return (await api.get<{events:number;errors:number;services:number;p95_ms:number;buckets:{time:number;events:number;errors:number}[];by_service:{name:string;count:number}[]}>('/api/summary',{signal:cancel,params:{from:to-Number(range),to,signal,service,trace_id:trace,search:params.get('search')||''}})).data;},refetchInterval:paused?false:10000,retry:1});
 const agents=useQuery({queryKey:['agents',user?.tenant],queryFn:async({signal})=>(await api.get<Agent[]>('/api/agents',{signal})).data,refetchInterval:10000,enabled:!signal});
 const events=useMemo(()=>query.data?.events||[],[query.data]);
 const chart=useMemo(()=>(summary.data?.buckets||[]).map(b=>({...b,time:new Date(b.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})})),[summary.data]);
 const p95=summary.data?.p95_ms; const title=topology?'Service dependencies':signal?signalNames[signal]:'Your systems, connected.';
 function update(key:string,value:string){setParams(prev=>{const next=new URLSearchParams(prev);if(value)next.set(key,value);else next.delete(key);if(key!=='cursor')next.delete('cursor');return next;});}
 async function save(){try{await api.post('/api/dashboards',{name:`${title} · ${new Date().toLocaleDateString()}`,signal,range,service,search:params.get('search')||'',path:window.location.pathname});setMessage('View saved to Workspace.');}catch{setMessage('Could not save view. Administrator permission is required.');}}
 return <DashboardLayout><div className="page-heading"><div><p className="eyebrow">{topology?'DEPENDENCIES':signal?'EXPLORER':'OBSERVABILITY OVERVIEW'}</p><h1>{title}</h1><p className="muted">{signal==='finance'?'Follow transaction lifecycles with exact amounts and source identifiers.':signal==='agent'?'Inspect model calls, tool execution and distributed handoffs.':'Follow the evidence from a signal to its source.'}</p></div><button onClick={()=>void save()}><Save size={15}/>Save view</button></div>
 <div className="query-toolbar"><form onSubmit={e=>{e.preventDefault();update('search',search)}}><Search size={16}/><input aria-label="Search telemetry" placeholder="Search service, event or attribute…" value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit">Search</button></form><select aria-label="Time range" value={range} onChange={e=>update('range',e.target.value)}><option value="900000">Last 15 minutes</option><option value="3600000">Last hour</option><option value="86400000">Last 24 hours</option><option value="604800000">Last 7 days</option></select><button onClick={()=>update('paused',paused?'':'true')}>{paused?'Resume':'Pause'}</button><button aria-label="Refresh telemetry" onClick={()=>{void query.refetch();void summary.refetch();}}><RefreshCw size={16}/></button></div>
 {(service||trace)&&<div className="filter-row">{service&&<button onClick={()=>update('service','')}>Service: {service}<X size={13}/></button>}{trace&&<button onClick={()=>update('trace_id','')}>Trace: {trace}<X size={13}/></button>}</div>}
 {message&&<div role="status" className="notice">{message}<button aria-label="Dismiss" onClick={()=>setMessage('')}><X size={14}/></button></div>}
 {summary.isError&&<p className="error-banner">Window summary unavailable. Event rows may still be available.</p>}
 {query.isError&&<div role="alert" className="error-banner">Telemetry could not be refreshed. {query.data?'Last successful results are shown below.':'Check your connection and permissions.'}<button onClick={()=>void query.refetch()}>Retry</button></div>}
 <div className="freshness"><span className={query.isError?'status-dot error':'status-dot'}/>{query.isPending?'Connecting…':query.isError?'Connection interrupted':paused?'Refresh paused':`Updated ${new Date(query.dataUpdatedAt).toLocaleTimeString()}`}<span>UTC offsets follow your browser timezone</span></div>
 <div className="kpi-grid">{[['Events in window',summary.data?formatNumber(summary.data.events):'—'],['Services in window',summary.data?String(summary.data.services):'—'],['Errors in window',summary.data?String(summary.data.errors):'—'],['Span p95 in window',p95?`${p95.toFixed(1)} ms`:'—']].map(([label,value])=><section key={label} className="kpi"><p>{label}</p><strong>{query.isPending?'—':value}</strong><span className="kpi-line"/></section>)}</div>
 {query.data?.next_cursor&&<p className="notice">More event rows are available. Charts aggregate the full time window; the table is paginated.</p>}
 <div className="analysis-grid"><section className="panel"><div className="panel-heading"><h2>Signal activity</h2><span className="legend"><i/>Events <i className="pink"/>Errors</span></div><div className="chart-area">{summary.data?.events?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="eventsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a6e86b" stopOpacity={.3}/><stop offset="100%" stopColor="#a6e86b" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#28312d" vertical={false}/><XAxis dataKey="time" stroke="#89968f" fontSize={12}/><YAxis allowDecimals={false} stroke="#89968f" fontSize={12}/><Tooltip contentStyle={{background:'#161c19',border:'1px solid #344138'}}/><Area type="monotone" dataKey="events" stroke="#a6e86b" fill="url(#eventsFill)" isAnimationActive={false}/><Area type="monotone" dataKey="errors" stroke="#f59caf" fill="transparent" isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<Empty loading={query.isPending}/>}</div></section><section className="panel"><div className="panel-heading"><h2>Service distribution</h2><span>Records</span></div><div className="chart-area">{summary.data?.events?<ResponsiveContainer width="100%" height="100%"><BarChart data={(summary.data?.by_service||[]).slice(0,8)} layout="vertical"><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={110} stroke="#abb8af" fontSize={12}/><Tooltip contentStyle={{background:'#161c19'}}/><Bar dataKey="count" fill="#93b8fb" radius={[0,3,3,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer>:<Empty loading={query.isPending}/>}</div></section></div>
 {topology?<Topology events={events} onService={value=>update('service',value)}/>:<section className="panel"><div className="panel-heading"><h2>{signal?signalNames[signal]:'Event stream'}</h2><span>{events.length} records · newest first</span></div><div className="table-scroll"><table><thead><tr><th>Time</th><th>Service / event</th><th>Signal</th><th>{signal==='finance'?'Amount':'Duration / value'}</th><th>Status</th><th/></tr></thead><tbody>{events.map(event=><tr key={event.id}><td className="mono">{new Date(event.time).toLocaleTimeString()}</td><td><button className="text-button event-name" onClick={()=>setSelected(event)}>{event.name||'Unnamed event'}</button><button className="service-link" onClick={()=>update('service',event.service)}>{event.service}</button></td><td><span className="tag">{event.signal}</span></td><td className="mono">{signal==='finance'?`${event.attributes.amount} ${event.attributes.currency}`:event.duration_ms>0?`${event.duration_ms.toFixed(2)} ms`:event.attributes.exact_value||event.value||'—'}</td><td><span className={`status-label ${event.status==='error'?'bad':''}`}>{event.status||'observed'}</span></td><td><button aria-label={`Inspect ${event.name}`} onClick={()=>setSelected(event)}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>{!events.length&&<Empty loading={query.isPending}/>}<div className="pagination"><button disabled={!cursor} onClick={()=>update('cursor','')}>Newest records</button><button disabled={!query.data?.next_cursor} onClick={()=>update('cursor',query.data?.next_cursor||'')}>Older records <ChevronRight size={15}/></button></div></section>}
 {!signal&&<section className="panel"><div className="panel-heading"><h2>Collector fleet</h2><span>{agents.data?.length||0} registered</span></div>{agents.isError?<p className="error-banner">Inventory unavailable</p>:agents.data?.length?<div className="table-scroll"><table><thead><tr><th>Agent</th><th>Version</th><th>Collection</th><th>Last seen</th></tr></thead><tbody>{agents.data.map(ag=><tr key={ag.id}><td className="mono">{ag.id}</td><td>{ag.version}</td><td>{agents.dataUpdatedAt-ag.seen>300000?'Offline':ag.collection}</td><td>{new Date(ag.seen).toLocaleString()}</td></tr>)}</tbody></table></div>:<p className="empty">No collectors registered. <Link to="/docs">Connect a collector →</Link></p>}</section>}
 {signal==='finance'&&<Reconciliation range={range}/>} 
 {selected&&<EventDetail event={selected} onClose={()=>setSelected(null)}/>}</DashboardLayout>;
}
function Empty({loading=false}:{loading?:boolean}) {return <div className="empty"><Activity size={24}/><h3>{loading?'Loading signals…':'No observations in this window'}</h3><p>{loading?'Fetching your workspace data.':'Connect a collector, expand the time range, or clear your filters.'}</p>{!loading&&<Link to="/docs">Set up ingestion →</Link>}</div>;}
function Topology({events,onService}:{events:TelemetryEvent[];onService:(s:string)=>void}) {const edges=new Map<string,{from:string;to:string;count:number;errors:number}>();for(const e of events){const parent=events.find(p=>p.span_id&&p.span_id===e.parent_id&&p.trace_id===e.trace_id);const from=parent?.service||e.attributes['source.service'];const to=e.attributes['destination.service']||e.service;if(!from||from===to)continue;const key=from+'→'+to;const edge=edges.get(key)||{from,to,count:0,errors:0};edge.count++;if(e.status==='error')edge.errors++;edges.set(key,edge);}return <section className="panel"><div className="panel-heading"><h2>Observed dependencies</h2><span>Derived from span parents and flow attributes on this page</span></div>{edges.size?<div className="dependency-grid">{[...edges.values()].map(edge=><button key={edge.from+edge.to} className="dependency" onClick={()=>onService(edge.to)}><span>{edge.from}</span><span className="edge-line">{edge.count} calls →</span><span>{edge.to}</span><small>{edge.errors} errors</small></button>)}</div>:<p className="empty">No linked spans or service flow attributes in these results. Dependencies are never inferred from sample data.</p>}</section>;}
function EventDetail({event,onClose}:{event:TelemetryEvent;onClose:()=>void}) {
 const panel=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;panel.current?.querySelector<HTMLButtonElement>('button')?.focus();return ()=>previous?.focus();},[]);
 const {user}=useAuth();const trace=useQuery({queryKey:['trace',user?.tenant,event.trace_id],enabled:!!event.trace_id,queryFn:async({signal})=>(await api.get<EventPage>('/api/events',{signal,params:{trace_id:event.trace_id,from:event.time-86400000,to:event.time+86400000,limit:1000}})).data});const spans=(trace.data?.events||[]).filter(e=>e.span_id).sort((a,b)=>a.time-b.time);const start=spans[0]?.time||event.time;const length=Math.max(1,...spans.map(s=>s.time-start+s.duration_ms));return <div className="detail-backdrop" onClick={onClose}><section ref={panel} className="detail-panel" role="dialog" aria-modal="true" aria-label="Event detail" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=panel.current?.querySelectorAll<HTMLElement>('button, a[href], input, select, [tabindex="0"]');if(items?.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}}><div className="panel-heading"><span className="eyebrow">EVENT DETAIL</span><button autoFocus aria-label="Close detail" onClick={onClose}><X size={20}/></button></div><h2>{event.name}</h2><p className="muted">{event.service} · {new Date(event.time).toLocaleString()}</p><code className="identifier">{event.trace_id||event.id}</code>{event.trace_id&&<><h3>Trace waterfall</h3>{trace.isError?<p className="error-banner">Trace unavailable</p>:spans.map(s=><div className="waterfall-row" key={s.id}><span title={s.name}>{s.name}{s.parent_id&&!spans.some(p=>p.span_id===s.parent_id)?' (parent missing)':''}</span><div><i style={{marginLeft:`${Math.min(95,(s.time-start)/length*100)}%`,width:`${Math.max(1,s.duration_ms/length*100)}%`,background:s.status==='error'?'#f59caf':'#a6e86b'}}/></div><small>{s.duration_ms.toFixed(1)}ms</small></div>)}{trace.data?.next_cursor&&<p className="notice">Trace exceeds 1,000 records; waterfall is partial.</p>}</>}<h3>Attributes</h3><dl className="attribute-list">{Object.entries(event.attributes).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section></div>;}

function Reconciliation({range}:{range:string}) {const {user}=useAuth();const query=useQuery({queryKey:['reconciliation',user?.tenant,range],queryFn:async({signal})=>{const to=Date.now();return (await api.get<{transactions:{id:string;currency:string;amount:string;state:string;issues:string[];events:number}[];partial:boolean;settled_totals:Record<string,string>}>('/api/finance/reconciliation',{signal,params:{from:to-Number(range),to}})).data;},refetchInterval:15000});return <section className="panel"><div className="panel-heading"><h2>Transaction sequence inspection</h2><span>Bounded operational view · not a ledger</span></div>{query.isError?<p className="error-banner">Reconciliation unavailable.</p>:<><div className="table-scroll"><table><thead><tr><th>Transaction</th><th>Latest state</th><th>Exact amount</th><th>Sequence checks</th></tr></thead><tbody>{query.data?.transactions.map(tx=><tr key={tx.id}><td className="mono">{tx.id}</td><td>{tx.state}</td><td>{tx.amount} {tx.currency}</td><td>{tx.issues.length?tx.issues.join(' · '):'No gaps within observed events'}</td></tr>)}</tbody></table></div>{query.data?.partial&&<p className="notice">This inspection covers the latest 1,000 events. Expand source coverage before drawing accounting conclusions.</p>}</>}</section>;}