import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/api/client';
import type { Agent } from './types';
import { QueryState } from './QueryState';
import { formatTime } from './state';

interface Stage {name:string;state:string;accepted?:number;rejected?:number;errors?:number;in_flight?:number;lag?:number;queue_age_ms?:number;writes?:number;latency_ms_total?:number}
interface Pipeline {configured:boolean;scope?:string;timestamp?:number;stages:Stage[]}
function collectorState(agent:Agent,now:number){const age=now-agent.seen;const metrics=agent.metrics||{};if(age>300000)return{label:'Collector unavailable',tone:'bad'};if(Number(metrics.queue_depth||metrics.queue_utilization||0)>0)return{label:'Exporter queueing',tone:'warn'};return{label:agent.collection||'Collector reporting',tone:'good'}}
export function FleetHealth({agents,loading,error,timezone}:{agents?:Agent[];loading:boolean;error:boolean;timezone:string}) {
  const pipeline=useQuery({queryKey:['pipeline-health'],queryFn:async({signal})=>(await api.get<Pipeline>('/api/pipeline-health',{signal})).data,refetchInterval:15000}); const [now]=useState(()=>Date.now());
  return <><section className="panel"><div className="panel-heading"><div><h2>Collector fleet</h2><span>Per-workspace heartbeats and exporter metrics</span></div></div>{loading?<QueryState kind="loading"/>:error?<QueryState kind="failed" title="Inventory unavailable"/>:agents?.length?<div className="table-scroll"><table><thead><tr><th>Collector</th><th>Version</th><th>State</th><th>Last seen</th></tr></thead><tbody>{agents.map(agent=>{const state=collectorState(agent,now);return<tr key={agent.id}><td className="mono">{agent.id}</td><td>{agent.version}</td><td><span className={`health ${state.tone}`}>{state.label}</span></td><td>{formatTime(agent.seen,timezone,true)}</td></tr>})}</tbody></table></div>:<QueryState kind="empty" title="No collectors registered" detail="No fleet status can be inferred without inventory."/>}</section><section className="panel"><div className="panel-heading"><div><h2>Deployment pipeline health</h2><span>Admin-only, real process counters · refreshes every 15 seconds</span></div></div>{pipeline.isPending?<QueryState kind="loading"/>:pipeline.isError?<QueryState kind="denied" title="Pipeline health unavailable" detail="This deployment requires an owner or administrator role."/>:!pipeline.data?.configured?<QueryState kind="empty" title="Pipeline metrics not configured"/>:<div className="health-grid">{pipeline.data.stages.map(stage=><article key={stage.name}><span className={`health ${stage.state==='healthy'?'good':'bad'}`}>{stage.state}</span><h3>{stage.name}</h3><dl>{Object.entries(stage).filter(([key])=>key!=='name'&&key!=='state').map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{value}</dd></div>)}</dl></article>)}</div>}</section></>;
}
