import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Braces, Info } from 'lucide-react';
import { api } from '@/api/client';
import type { AnalyticalResponse } from './types';
import { useInvestigationState } from './state';
import { QueryState } from './QueryState';
import { VisualizationStudio } from './visualizations';
import { compatibleVisualizations, type VisualizationId } from './visualizationRegistry';

export function MetricsExplorer() {
  const {state,update,params}=useInvestigationState();
  const [name,setName]=useState(''); const [operation,setOperation]=useState('avg'); const [group,setGroup]=useState('service'); const [unit,setUnit]=useState('auto'); const [formula,setFormula]=useState('A'); const [compare,setCompare]=useState(true); const [submittedFormula,setSubmittedFormula]=useState('A');
  const requested=(params.get('visualization')||'line') as VisualizationId;
  const visualization=compatibleVisualizations('metric').some(item=>item.id===requested)?requested:'line';
  const query=useQuery({queryKey:['analytical',state.range,state.service,name,operation,group,compare,submittedFormula],enabled:operation!=='rate'||!!name,queryFn:async({signal})=>{const to=Date.now();return(await api.post<AnalyticalResponse>('/api/query',{version:'v1',signal:'metric',from:to-Number(state.range),to,service:state.service,name,operation,group_by:group?[group]:[],formula:submittedFormula,step_ms:0,compare_previous:compare,exemplars:true,budget:{max_rows:100000,max_bytes:16777216,max_cpu_ms:10000,timeout_ms:10000}},{signal})).data}});
  return <>
    <form className="metric-builder panel" onSubmit={event=>{event.preventDefault();setSubmittedFormula(formula)}}><div className="builder-intro"><Braces/><div><strong>Shared analytical query</strong><span>Changing the view below preserves this scope, formula, and server aggregation.</span></div></div><label>Metric<input value={name} onChange={event=>setName(event.target.value)} placeholder="Required for counter rate"/></label><label>Operation<select value={operation} onChange={event=>setOperation(event.target.value)}>{['avg','sum','min','max','rate','histogram','p50','p95','p99'].map(value=><option key={value}>{value}</option>)}</select></label><label>Group by<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">None</option><option>service</option><option>name</option><option>status</option></select></label><label>Unit<select value={unit} onChange={event=>setUnit(event.target.value)}><option>auto</option><option>ms</option><option>s</option><option>bytes</option><option>percent</option><option>count/s</option></select></label><label>Formula<input value={formula} onChange={event=>setFormula(event.target.value)} aria-describedby="formula-note"/></label><label className="check"><input type="checkbox" checked={compare} onChange={event=>setCompare(event.target.checked)}/>Previous window</label><button className="primary-action" type="submit">Run query</button><small id="formula-note"><Info/> Server formula syntax: A or A followed by one numeric +, −, ×, or ÷ transform.</small></form>
    {operation==='rate'&&!name?<QueryState kind="empty" title="Choose a counter metric" detail="The backend requires a metric name for reset-aware rates."/>:<section className="panel metric-result">{query.isPending?<QueryState kind="loading"/>:query.isError?<QueryState kind="failed" retry={()=>void query.refetch()}/>:query.data?.execution.partial?<QueryState kind="partial" detail={`Budget limit: ${(query.data.execution.partial_reasons||[]).join(', ')}`}/>:null}{query.data?<VisualizationStudio signal="metric" points={query.data.points||[]} visualization={visualization} onVisualizationChange={value=>update({visualization:value})} title={`${submittedFormula} · ${operation} ${name||'all metrics'}`}/>:null}{!query.isPending&&!query.data?.points?.length?<QueryState kind="empty"/>:null}<div className="query-foot"><span>{unit} · max 300 points</span><span>{query.data?`${query.data.execution.rows_scanned.toLocaleString()} rows scanned · ${query.data.execution.elapsed_ms} ms`:''}</span></div>{query.data?.comparison?.length?<p className="comparison-note">Comparison window returned {query.data.comparison.length} bounded points.</p>:null}{operation==='rate'?<p className="reset-note">Counter resets are handled server-side; negative deltas restart accumulation.</p>:null}<div className="exemplars">{(query.data?.points||[]).flatMap(point=>point.exemplars||[]).slice(0,12).map(id=><button key={id} onClick={()=>update({trace_id:id})}>Exemplar {id.slice(0,10)}…</button>)}</div></section>}
  </>;
}
