import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '@/api/client';
import type { AnalyticalResponse } from './types';
import { formatTime, useInvestigationState } from './state';
import { QueryState } from './QueryState';

const colors=['#b2eb78','#86b8ff','#f6a7ba','#e8c46a','#bca4ff'];
export function MetricsExplorer() {
  const {state,update}=useInvestigationState(); const [name,setName]=useState(''); const [operation,setOperation]=useState('avg'); const [group,setGroup]=useState('service'); const [unit,setUnit]=useState('auto'); const [formula,setFormula]=useState('A'); const [compare,setCompare]=useState(true); const [submittedFormula,setSubmittedFormula]=useState('A');
  const query=useQuery({queryKey:['analytical',state.range,state.service,name,operation,group,compare,submittedFormula],enabled:operation!=='rate'||!!name,queryFn:async({signal})=>{const to=Date.now();return(await api.post<AnalyticalResponse>('/api/query',{version:'v1',signal:'metric',from:to-Number(state.range),to,service:state.service,name,operation,group_by:group?[group]:[],formula:submittedFormula,step_ms:0,compare_previous:compare,exemplars:true,budget:{max_rows:100000,max_bytes:16777216,max_cpu_ms:10000,timeout_ms:10000}},{signal})).data}});
  const groups=useMemo(()=>[...new Set((query.data?.points||[]).map(point=>Object.values(point.group||{}).join(' · ')||'all'))],[query.data]);
  const rows=useMemo(()=>{const map=new Map<number,Record<string,number|string>>();for(const point of query.data?.points||[]){const row=map.get(point.time)||{time:point.time,label:formatTime(point.time,state.timezone)};row[Object.values(point.group||{}).join(' · ')||'all']=point.value;map.set(point.time,row)}return[...map.values()]},[query.data,state.timezone]);
  const histogram=useMemo(()=>(query.data?.points||[]).flatMap(point=>(point.histogram||[]).map(bucket=>({upper:bucket.upper,count:bucket.count,series:Object.values(point.group||{}).join(' · ')||'all'}))),[query.data]);
  return <><form className="metric-builder panel" onSubmit={event=>{event.preventDefault();setSubmittedFormula(formula)}}><label>Metric<input value={name} onChange={event=>setName(event.target.value)} placeholder="Required for counter rate"/></label><label>Operation<select value={operation} onChange={event=>setOperation(event.target.value)}>{['avg','sum','min','max','rate','histogram','p50','p95','p99'].map(value=><option key={value}>{value}</option>)}</select></label><label>Group by<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">None</option><option>service</option><option>name</option><option>status</option></select></label><label>Unit<select value={unit} onChange={event=>setUnit(event.target.value)}><option>auto</option><option>ms</option><option>s</option><option>bytes</option><option>percent</option><option>count/s</option></select></label><label>Formula<input value={formula} onChange={event=>setFormula(event.target.value)} aria-describedby="formula-note"/></label><label className="check"><input type="checkbox" checked={compare} onChange={event=>setCompare(event.target.checked)}/>Previous window</label><button type="submit">Apply formula</button><small id="formula-note">Server formula syntax: A or A followed by one numeric +, −, ×, or ÷ transform.</small></form>
    {operation==='rate'&&!name?<QueryState kind="empty" title="Choose a counter metric" detail="The backend requires a metric name for reset-aware rates."/>:<section className="panel"><div className="panel-heading"><div><h2>{submittedFormula} · {operation} {name||'all metrics'}</h2><span>{unit} · {groups.length} series · max 300 points</span></div>{query.data?<span>{query.data.execution.rows_scanned.toLocaleString()} rows · {query.data.execution.elapsed_ms} ms</span>:null}</div>{query.isPending?<QueryState kind="loading"/>:query.isError?<QueryState kind="failed" retry={()=>void query.refetch()}/>:query.data?.execution.partial?<QueryState kind="partial" detail={`Budget limit: ${(query.data.execution.partial_reasons||[]).join(', ')}`}/>:null}<div className="chart-area metric-chart">{operation==='histogram'&&histogram.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={histogram}><CartesianGrid stroke="#28312d"/><XAxis dataKey="upper"/><YAxis/><Tooltip/><Bar dataKey="count" fill={colors[0]}/></BarChart></ResponsiveContainer>:rows.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid stroke="#28312d" vertical={false}/><XAxis dataKey="label" minTickGap={40}/><YAxis width={60}/><Tooltip contentStyle={{background:'#151d18',border:'1px solid #36443a'}}/>{groups.slice(0,5).map((value,index)=><Line key={value} dataKey={value} stroke={colors[index]} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer>:!query.isPending?<QueryState kind="empty"/>:null}</div>{query.data?.comparison?.length?<p className="comparison-note">Comparison window returned {query.data.comparison.length} bounded points.</p>:null}{operation==='rate'?<p className="reset-note">Counter resets are handled server-side; negative deltas restart accumulation.</p>:null}<div className="exemplars">{(query.data?.points||[]).flatMap(point=>point.exemplars||[]).slice(0,12).map(id=><button key={id} onClick={()=>update({trace_id:id})}>Exemplar {id.slice(0,10)}…</button>)}</div></section>}
  </>;
}
