import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Network, Search, ZoomIn, ZoomOut } from 'lucide-react';
import { api } from '@/api/client';
import { useInvestigationState } from './state';
import { QueryState } from './QueryState';

interface Edge { source:string; destination:string; calls:number; errors:number; duration_ms:number }
interface TopologyResult { edges:Edge[]; clusters:Record<string,number>; next_cursor?:string; scanned:number; partial:boolean; partial_reason?:string }

export function Topology({onService}:{events?:unknown;onService:(service:string)=>void}) {
  const {state}=useInvestigationState(); const [filter,setFilter]=useState(''); const [zoom,setZoom]=useState(1); const [mode,setMode]=useState<'graph'|'table'>('graph'); const [cursor,setCursor]=useState('');
  const query=useQuery({queryKey:['topology',state.range,state.service,state.search,filter,cursor],queryFn:async({signal})=>{const to=Date.now();return (await api.get<TopologyResult>('/api/topology',{signal,params:{from:to-Number(state.range),to,service:state.service,search:`${state.search} ${filter}`.trim(),cursor,limit:500}})).data}});
  const edges=query.data?.edges||[]; const clusters=useMemo(()=>Object.entries(query.data?.clusters||{}).sort((a,b)=>b[1]-a[1]),[query.data]);
  return <section className="panel topology"><div className="panel-heading"><div><h2>Workspace service topology</h2><span>{query.data?.scanned||0} spans scanned · server aggregated · cursor bounded</span></div><div className="topology-controls"><label><Search size={14}/><input aria-label="Filter topology" value={filter} onChange={e=>{setFilter(e.target.value);setCursor('')}} placeholder="Filter services"/></label><button onClick={()=>setMode(mode==='graph'?'table':'graph')}>{mode==='graph'?'Table view':'Graph view'}</button><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.6,v-.2))}><ZoomOut/></button><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.8,v+.2))}><ZoomIn/></button></div></div>
    {query.isPending?<QueryState kind="loading"/>:query.isError?<QueryState kind="failed" retry={()=>void query.refetch()}/>:query.data?.partial?<QueryState kind="partial" detail={`Topology scan limited by ${query.data.partial_reason}. Filter or shorten the time range for complete evidence.`}/>:null}
    {!query.isPending&&!edges.length?<QueryState kind="empty" title="No observed dependencies" detail="The server found no parent or source/destination relationship in this scope."/>:mode==='table'?<div className="table-scroll"><table><thead><tr><th>Source</th><th>Destination</th><th>Calls</th><th>Errors</th><th>Average duration</th></tr></thead><tbody>{edges.map(edge=><tr key={edge.source+edge.destination}><td><button className="text-button" onClick={()=>onService(edge.source)}>{edge.source}</button></td><td><button className="text-button" onClick={()=>onService(edge.destination)}>{edge.destination}</button></td><td>{edge.calls}</td><td>{edge.errors}</td><td>{(edge.duration_ms/edge.calls).toFixed(1)} ms</td></tr>)}</tbody></table></div>:<div className="topology-canvas"><div className="cluster-strip">{clusters.slice(0,30).map(([name,count])=><span key={name}>{name} <b>{count}</b></span>)}</div><div className="edge-list" style={{transform:`scale(${zoom})`}}>{edges.slice(0,100).map(edge=><button key={edge.source+edge.destination} className="dependency" onClick={()=>onService(edge.destination)}><Network/><strong>{edge.source}</strong><span>{edge.calls} calls →</span><strong>{edge.destination}</strong><small>{edge.errors} errors · {(edge.duration_ms/edge.calls).toFixed(1)} ms avg</small></button>)}</div>{edges.length>100?<QueryState kind="partial" detail={`${edges.length-100} returned edges are available in table view.`}/>:null}</div>}
    <div className="pagination"><button disabled={!cursor} onClick={()=>setCursor('')}>First topology page</button><button disabled={!query.data?.next_cursor} onClick={()=>setCursor(query.data?.next_cursor||'')}>Next 500 edges →</button></div>
  </section>;
}
