import { useEffect, useMemo, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { GitFork, Link2, TriangleAlert, X } from 'lucide-react';
import { api } from '@/api/client';
import type { TelemetryEvent } from './types';
import { formatTime } from './state';
import { QueryState } from './QueryState';

interface TraceSpan extends TelemetryEvent {links:string[];missing_parent:boolean;late:boolean;critical:boolean;fan_out:number;fan_in:number}
interface TraceResponse {trace_id:string;spans:TraceSpan[];logs:TelemetryEvent[];metrics:TelemetryEvent[];partial:boolean;clock_skew_detected:boolean}

export function TraceDetail({event,timezone,onClose}:{event:TelemetryEvent;timezone:string;onClose:()=>void}) {
  const panel=useRef<HTMLElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;panel.current?.querySelector<HTMLElement>('button')?.focus();return()=>previous?.focus()},[]);
  const query=useQuery({queryKey:['trace-investigation',event.trace_id],enabled:!!event.trace_id,queryFn:async({signal})=>(await api.get<TraceResponse>('/api/trace',{signal,params:{trace_id:event.trace_id,from:event.time-86400000,to:event.time+86400000}})).data});
  const spans=query.data?.spans||[]; const start=Math.min(...spans.map(span=>span.time),event.time); const end=Math.max(...spans.map(span=>span.time+span.duration_ms),event.time+event.duration_ms); const length=Math.max(1,end-start);
  const related=useMemo(()=>[{label:'Logs',count:query.data?.logs.length||0},{label:'Metrics',count:query.data?.metrics.length||0}],[query.data]);
  return <div className="detail-backdrop" onMouseDown={onClose}><section ref={panel} className="detail-panel" role="dialog" aria-modal="true" aria-labelledby="trace-title" onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=panel.current?.querySelectorAll<HTMLElement>('button,a[href],[tabindex="0"]');if(items?.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}}>
    <div className="panel-heading"><div><span className="eyebrow">TRACE INVESTIGATION</span><h2 id="trace-title">{event.name}</h2></div><button aria-label="Close trace detail" onClick={onClose}><X/></button></div><div className="trace-meta"><code>{event.trace_id||event.id}</code><span>{formatTime(event.time,timezone,true)}</span></div>
    {query.isPending?<QueryState kind="loading"/>:query.isError?<QueryState kind="failed" retry={()=>void query.refetch()}/>:<><div className="trace-legend"><span className="critical">Server critical path</span><span className="error">Error</span><span><TriangleAlert size={13}/> missing parent / late / clock skew</span><span><Link2 size={13}/> span link</span></div>{query.data?.clock_skew_detected?<QueryState kind="stale" title="Clock skew detected" detail="A child timestamp precedes its observed parent; duration ordering remains unchanged."/>:null}<div className="waterfall">{spans.map((span,index)=><button className={`waterfall-row ${span.critical?'is-critical':''}`} key={span.id} onClick={()=>document.getElementById(`span-${index}`)?.scrollIntoView({behavior:'smooth'})}><span title={span.name}>{span.name}</span><div><i style={{marginLeft:`${Math.max(0,(span.time-start)/length*100)}%`,width:`${Math.max(1,span.duration_ms/length*100)}%`}} className={span.status==='error'?'error':''}/></div><small>{span.duration_ms.toFixed(1)} ms</small><em>{span.missing_parent?<TriangleAlert aria-label="Missing parent"/>:null}{span.late?<span>late</span>:null}{span.links.length?<Link2 aria-label={`${span.links.length} span links`}/>:null}{span.fan_out>1||span.fan_in>1?<GitFork aria-label={span.fan_out>1?'fan-out':'fan-in'}/>:null}</em></button>)}</div>{query.data?.partial?<QueryState kind="partial" detail="The dedicated trace contract reached its 10,000-record bound."/>:null}<h3>Related telemetry</h3><div className="related-grid">{related.map(item=><div key={item.label}><strong>{item.label}</strong><span>{item.count} correlated records</span></div>)}</div><h3>Spans and attributes</h3>{spans.map((span,index)=><details id={`span-${index}`} key={span.id}><summary>{span.service} / {span.name}</summary>{span.links.length?<p>Links: {span.links.join(', ')}</p>:null}<dl className="attribute-list">{Object.entries(span.attributes).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>)}</>}
  </section></div>;
}
