import { useMemo, useRef, useState } from 'react';
import { ChevronRight, Download, Expand, FileJson, Info, RotateCcw, Table2, ZoomIn, ZoomOut } from 'lucide-react';
import type { QueryPoint } from './types';
import { compatibleVisualizations, visualizationRegistry, type VisualizationId } from './visualizationRegistry';

const palette=['#ffb547','#7dcfff','#c8f08a','#e99aae','#aa9cff'];
const normalized=(values:number[])=>{const max=Math.max(...values.map(Math.abs),1);return values.map(value=>value/max)};

function SeriesSvg({points,type}:{points:QueryPoint[];type:'line'|'area'|'stacked'}) {
  const values=normalized(points.slice(-100).map(point=>point.value));
  const path=values.map((value,index)=>`${index?'L':'M'} ${8+(index/Math.max(1,values.length-1))*584} ${165-value*135}`).join(' ');
  return <svg className="viz-svg" viewBox="0 0 600 190" role="img"><title>{type} chart with {points.length} bounded server-aggregated points</title><g className="grid-lines">{[30,75,120,165].map(y=><line key={y} x1="8" x2="592" y1={y} y2={y}/>)}</g>{type!=='line'?<path d={`${path} L592 175 L8 175Z`} fill="url(#area-fill)"/>:null}<defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor={palette[0]} stopOpacity=".38"/><stop offset="1" stopColor={palette[0]} stopOpacity=".02"/></linearGradient></defs><path d={path} fill="none" stroke={palette[0]} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>;
}

function Distribution({points}:{points:QueryPoint[]}) {const buckets=(points.flatMap(point=>point.histogram||[]).slice(0,40));const max=Math.max(...buckets.map(item=>item.count),1);return <div className="distribution" role="img" aria-label={`Histogram with ${buckets.length} bounded buckets`}>{buckets.length?buckets.map((bucket,index)=><i key={`${bucket.upper}-${index}`} style={{height:`${Math.max(3,bucket.count/max*100)}%`}} title={`≤ ${bucket.upper}: ${bucket.count}`}/>):normalized(points.slice(-32).map(point=>point.value)).map((value,index)=><i key={index} style={{height:`${Math.max(3,value*100)}%`}}/>)}</div>}
function Heatmap({points}:{points:QueryPoint[]}) {const values=normalized(points.slice(-72).map(point=>point.value));return <div className="heatmap" role="img" aria-label={`Heat map of ${values.length} bounded points`}>{values.map((value,index)=><i key={index} style={{opacity:.12+value*.88}}/>)}</div>}
function UnavailableEvidence({detail}:{detail:string}) {return <div className="viz-evidence-unavailable" role="status"><Info/><strong>Required dimensions were not returned.</strong><p>{detail}</p></div>}
function Tunnel({points}:{points:QueryPoint[]}) {const stages=points.filter(point=>point.group?.stage).slice(0,12);const max=Math.max(...stages.map(point=>point.count),1);if(!stages.length)return <UnavailableEvidence detail="Tunnel view requires server aggregates grouped by an explicit stage field (accepted, validated, queued, processed, stored, queried, rejected, retried, or dropped)."/>;return <div className="tunnel-view" role="img" aria-label={`Stage volume tunnel from ${stages.length} returned stage aggregates`}><p><Info/> Width is proportional to the returned count for each explicit stage.</p>{stages.map(point=><div key={`${point.group?.stage}-${point.time}`} style={{width:`${Math.max(22,point.count/max*100)}%`}}><span>{point.group?.stage}</span><b>{point.count.toLocaleString()}</b></div>)}</div>}
function Radar({points}:{points:QueryPoint[]}) {const values=normalized([points.at(-1)?.p50||40,points.at(-1)?.p95||68,points.at(-1)?.p99||83,points.at(-1)?.count||54,points.at(-1)?.value||72]);const positions=[[150,20],[270,105],[225,245],[75,245],[30,105]];const shape=positions.map(([x,y],i)=>{const dx=x-150,dy=y-140,v=.25+values[i]*.7;return `${150+dx*v},${140+dy*v}`}).join(' ');return <div className="radar-view"><svg viewBox="0 0 300 270" role="img"><title>Normalized comparison. Axes are independently normalized from zero to one.</title>{[.33,.66,1].map(scale=><polygon key={scale} points={positions.map(([x,y])=>`${150+(x-150)*scale},${140+(y-140)*scale}`).join(' ')}/>) }<polygon className="radar-value" points={shape}/></svg><p>Normalized 0–1 per dimension. Absolute values are not directly comparable.</p></div>}
function pointLabel(point:QueryPoint,index:number){return point.group?.name||point.group?.service||point.group?.agent||point.group?.provider||point.group?.state||point.group?.stage||`series ${index+1}`}
function TrackView({signal,points}:{signal:string;points:QueryPoint[]}) {const rows=points.slice(-12);const [zoom,setZoom]=useState(1);const [selected,setSelected]=useState<number>();const [collapsed,setCollapsed]=useState<Set<string>>(()=>new Set());if(!rows.length)return <UnavailableEvidence detail="Transmission view needs bounded event-time aggregates. No points were returned for this scope."/>;const start=Math.min(...rows.map(point=>point.time)),end=Math.max(...rows.map(point=>point.time),start+1);const maxDuration=Math.max(...rows.map(point=>point.p95||point.value||1),1);const toggle=(label:string)=>setCollapsed(value=>{const next=new Set(value);if(next.has(label))next.delete(label);else next.add(label);return next});return <div className="track-shell"><div className="track-controls" aria-label="Timeline controls"><button aria-label="Zoom out timeline" disabled={zoom<=1} onClick={()=>setZoom(value=>Math.max(1,value/1.5))}><ZoomOut/></button><output>{zoom.toFixed(1)}×</output><button aria-label="Zoom in timeline" disabled={zoom>=4} onClick={()=>setZoom(value=>Math.min(4,value*1.5))}><ZoomIn/></button><button aria-label="Reset timeline zoom" onClick={()=>setZoom(1)}><RotateCcw/></button><span>Snaps to returned event boundaries</span></div><div className="track-scroll"><div className="track-view" style={{width:`${zoom*100}%`}} role="img" aria-label={`${signal} timeline from ${rows.length} returned aggregate points`}>{rows.map((point,index)=>{const label=pointLabel(point,index),left=((point.time-start)/(end-start))*82,width=Math.max(4,Math.min(28,((point.p95||point.value||1)/maxDuration)*24));return <div key={`${label}-${point.time}`} className={selected===index?'is-selected':''}><button aria-expanded={!collapsed.has(label)} onClick={()=>toggle(label)}><ChevronRight/>{label}</button>{!collapsed.has(label)?<button className="track-clip" onClick={()=>setSelected(index)} style={{left:`${left+14}%`,width:`${width}%`}}><b>{(point.p95||point.value).toLocaleString()} · {point.count.toLocaleString()} events</b></button>:null}</div>})}<small>Position = event time · width = returned value/p95 · no parent link is inferred</small></div></div><div className="track-minimap" aria-label="Timeline minimap">{rows.map((point,index)=><i key={`${point.time}-${index}`} style={{left:`${((point.time-start)/(end-start))*96}%`}}/>)}</div>{selected!==undefined?<dl className="track-detail"><div><dt>Track</dt><dd>{pointLabel(rows[selected],selected)}</dd></div><div><dt>Event time</dt><dd>{new Date(rows[selected].time).toISOString()}</dd></div><div><dt>Count</dt><dd>{rows[selected].count.toLocaleString()}</dd></div><div><dt>Value</dt><dd>{rows[selected].value.toLocaleString()}</dd></div></dl>:null}</div>}
function FlowView({kind,points}:{kind:'pipeline'|'topology'|'agent-workflow'|'finance-lifecycle';points:QueryPoint[]}) {const edges=points.filter(point=>point.group?.source&&point.group?.destination).slice(0,20);const nodes=[...new Set(edges.flatMap(point=>[point.group!.source,point.group!.destination]))].slice(0,8);if(edges.length===0)return <UnavailableEvidence detail={`${kind} requires explicit source and destination dimensions from the backend. This aggregate contains no evidence-backed edges, so Sennet will not draw a causal route.`}/>;return <div className={`flow-view flow-view--${kind}`}><svg viewBox="0 0 700 190" role="img"><title>{kind} with {nodes.length} evidence-backed nodes and {edges.length} returned edges</title>{edges.map((edge,index)=>{const source=nodes.indexOf(edge.group!.source),destination=nodes.indexOf(edge.group!.destination);return <path key={`${edge.group!.source}-${edge.group!.destination}-${index}`} d={`M${55+source*80} 95 Q${55+(source+destination)*40} ${index%2?50:140} ${55+destination*80} 95`}/>})}{nodes.map((label,index)=><g key={label} transform={`translate(${55+index*80} 95)`}><circle r="15"/><text y={index%2?42:-30} textAnchor="middle">{label}</text></g>)}</svg><table><caption>Accessible edge evidence</caption><thead><tr><th>Source</th><th>Destination</th><th>Count</th><th>Value</th></tr></thead><tbody>{edges.map((edge,index)=><tr key={index}><td>{edge.group?.source}</td><td>{edge.group?.destination}</td><td>{edge.count}</td><td>{edge.value}</td></tr>)}</tbody></table></div>}

export function VisualizationStudio({signal,points,visualization,onVisualizationChange,title='Query result'}:{signal:string;points:QueryPoint[];visualization:VisualizationId;onVisualizationChange:(value:VisualizationId)=>void;title?:string}) {
  const container=useRef<HTMLDivElement>(null);const [table,setTable]=useState(false);const options=useMemo(()=>compatibleVisualizations(signal),[signal]);const definition=visualizationRegistry.find(item=>item.id===visualization);const supported=options.some(item=>item.id===visualization);
  const download=()=>{const blob=new Blob([JSON.stringify(points,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=href;anchor.download='sennet-query-result.json';anchor.click();URL.revokeObjectURL(href)};
  const fullscreen=()=>void container.current?.requestFullscreen?.();
  return <div className="visualization-studio" ref={container}><header className="viz-toolbar"><div><strong>{title}</strong><span>{points.length} aggregated points · {definition?.description}</span></div><label>View<select aria-label="Visualization type" value={visualization} onChange={event=>onVisualizationChange(event.target.value as VisualizationId)}>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><button title="Inspect data" aria-pressed={table} onClick={()=>setTable(value=>!value)}><Table2/></button><button title="Download JSON" onClick={download}><Download/></button><button title="Fullscreen" onClick={fullscreen}><Expand/></button></header>{!supported?<div className="unsupported-state"><Info/><strong>{definition?.label||visualization} is unavailable for {signal} signals.</strong><p>Choose a compatible view. Sennet does not invent missing dimensions.</p></div>:table?<div className="inspect-data"><FileJson/><pre>{JSON.stringify(points.slice(0,30),null,2)}</pre><small>Inspect view is capped at 30 of {points.length} returned points.</small></div>:<div className="viz-stage">{visualization==='line'||visualization==='area'||visualization==='stacked'?<SeriesSvg points={points} type={visualization}/>:visualization==='distribution'?<Distribution points={points}/>:visualization==='heatmap'?<Heatmap points={points}/>:visualization==='tunnel'?<Tunnel points={points}/>:visualization==='radar'?<Radar points={points}/>:visualization==='transmission'?<TrackView signal={signal} points={points}/>:visualization==='pipeline'||visualization==='topology'||visualization==='agent-workflow'||visualization==='finance-lifecycle'?<FlowView kind={visualization} points={points}/>:null}</div>}</div>;
}
