import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Activity, ArrowRight } from 'lucide-react';
export function LoginPage() {
 const auth = useAuth(); const navigate = useNavigate();
 const [key,setKey] = useState(''); const [email,setEmail] = useState(''); const [password,setPassword] = useState(''); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
 async function submit(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); navigate('/dashboard'); } catch { setError('Sign-in failed. Check your credential and server connection.'); } finally { setBusy(false); } }
 return <div className="login-shell"><Link to="/" className="brand"><Activity/> sennet<span> / observability</span></Link><main className="login-panel"><p className="eyebrow">YOUR SYSTEMS, IN CONTEXT</p><h1>Open your workspace.</h1><p className="muted">Connect with a scoped access key issued by your administrator.</p><form onSubmit={e=>{e.preventDefault();void submit(()=>auth.loginWithKey(key));}}><label htmlFor="access-key">Access key</label><input id="access-key" type="password" required autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk_…"/><button className="primary" disabled={busy}>Connect workspace <ArrowRight size={16}/></button></form>{auth.isFirebaseEnabled && <><div className="divider">or sign in with your account</div><form onSubmit={e=>{e.preventDefault();void submit(()=>auth.login(email,password));}}><label htmlFor="email">Email</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Password</label><input id="password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy}>Sign in</button></form><button disabled={busy} onClick={()=>void submit(auth.loginWithGoogle)}>Google</button><button disabled={busy} onClick={()=>void submit(auth.loginWithGithub)}>GitHub</button><Link to="/register">Create account</Link></>}{error&&<p role="alert" className="error-banner">{error}</p>}<Link to="/docs">Connection and installation guide →</Link></main></div>;
}
