apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sennet
resources:
  - namespace.yaml
  - gateway.yaml
  - storage-consumer.yaml
  - query-control.yaml
  - all-in-one.yaml
images:
  - name: sennet/backend
    newTag: local
